---
- include: webupd8.yml
  when: '"oracle-java8-installer" in java_versions'

- include: java10.yml
  when: '"oracle-java10-installer" in java_versions'

- name: Automatically select the Oracle License
  tags: java
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
  changed_when: false

- name: Install Oracle Java
  tags: java
  apt: name="{{ item }}" update_cache=yes state=latest
#  when: item|search("^oracle")
  with_items: "{{ java_versions }}"

- name: Java | Update Env
  alternatives:
    name: java
    path: "/usr/lib/jvm/java-{{ java_default_version }}-oracle/bin/java"

- name: Java | Ensure Defaults on etc/alternatives systems
  file:
    src: /usr/lib/jvm/java-{{ java_default_version }}-oracle
    dest: /usr/lib/jvm/default-java
    force: yes
    state: link

- name: Java | Export environment variables
  template:
    src: jdk.sh.j2
    dest: /etc/profile.d/jdk.sh

- name: Java | Source environment variables
  shell: source /etc/profile
  args:
    executable: /bin/bash
  changed_when: false
  tags:
    skip_ansible_lint